### ISSUE TITLE
Cut a new release tag to bring bug fixes to latest

### ISSUE THREAD

**Issue by nathanperkins** [fatih/errwrap#19]
The current latest release still has the old broken x/tools. Can you cut a new tag so install@latest will have the bugfixes?

```
$ go install github.com/fatih/errwrap@latest

$ errwrap --fix ./e2e/...
errwrap: internal error: package "strings" without types was imported from "<snip>"

$ go install github.com/fatih/errwrap@d3e5aba47356be0b258b309dbe2c30b7c195521a

$ errwrap --fix ./e2e/...
<snip>:24:15: call could wrap the error with error-wrapping directive %w
...
```

**Comment by fatih** [comment]
Hi @nathanperkins 

Thank you for opening an issue. I've updated the dependencies and cut a new release: https://github.com/fatih/errwrap/releases/tag/v1.5.0

Let me know if you still see issues.
