### ISSUE TITLE
make it part of golang ci lint

### ISSUE THREAD

**Issue by kishaningithub** [fatih/errwrap#2]
IMHO this great tool will reach a far wider audience if it is made part of https://github.com/golangci/golangci-lint

**Comment by fatih** [comment]
Thank for your feedback. Unfortunately I don't have the bandwith or time to work on this. This is a side project I've done in my spare times. Feel free to use it this way. Thank you.

**Comment by ferhatelmas** [comment]
@fatih  I can try to implement the integration. It might help with larger adaptation.

However, `errwrap.Analyzer` must be put outside of the internal package so that it could be used by the golangci-lint. Good for a PR?
