### ISSUE TITLE
Leading whitespace corrupted

### ISSUE THREAD

**Issue by tmm1** [fatih/errwrap#3]
<pre>

        if err := os.Rename(sourceFilename, destinationFilename); err
 != nil {
-               err = fmt.Errorf("Could not move file: %v to %v: %v",
-                       sourceFilename, destinationFilename, err)
+               err = fmt.Errorf("Could not move file: %v to %v: %w",
+       sourceFilename, destinationFilename, err)
                log.Add("err", err)

</pre>

**Comment by fatih** [comment]
Thanks, I assume you're meaning that the code is not correctly formatted? This is a valid Go code though. Seems like `go/analysis` doesn't formatting fixes. I'll ask around whether this is intended or not. 

/cc @matloob

**Comment by fatih** [comment]
@matloob is working on a fix that will format source code that are modified with the `-fix` flag: https://go-review.googlesource.com/c/tools/+/209861

**Comment by fatih** [comment]
The latest master includes now the fix. Thank you for your report again. Also released a new version with it: https://github.com/fatih/errwrap/releases/tag/v1.1.0
