### ISSUE TITLE
errwrap ./... not working

### ISSUE THREAD

**Issue by tmm1** [fatih/errwrap#4]
<pre>
$ head -1 go.mod
module github.com/tmm1/myproj

$ errwrap ./...
errwrap: ./... matched no packages
</pre>

**Comment by fatih** [comment]
Thanks for the feedback but the issue lacks a lot of context and is poorly written. It works for me (try it in https://github.com/fatih/gomodifytags repo). I'm not sure what you're expecting. Please provide a reproducible repo so I can check it. Thank you.

**Comment by tmm1** [comment]
Sorry about the brevity. I was on my phone trying to log an issue quickly over the weekend.

I tried a few other projects and errwrap seems to work, but on one of my private programs I only get the "matched no packages" error message for some reason. 

I tried `errwrap -debug fpstv ./...` but it didn't say much else:

```
10:33:19.737261 load [./...]
10:33:22.778641 ./... matched no packages
```

I'll see if I can narrow down to a simple repro.
