### ISSUE TITLE
How about enabling workflows for PRs?

### ISSUE THREAD

**Issue by ferhatelmas** [fatih/errwrap#6]
I am new to workflows but I think it might be nice to enable it for PRs, too? 

Or is it supposed to run on forks? If so, it's a bit inconvenient to see if PRs follow the expected standards.

**Comment by fatih** [comment]
Closed with https://github.com/fatih/errwrap/pull/7 

Added the `pull_request` event to the `on` field: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
